Update ffmpeg-recorder

diff --git a/bin/.local/bin/ffmpeg-recorder b/bin/.local/bin/ffmpeg-recorder
--- a/bin/.local/bin/ffmpeg-recorder
+++ b/bin/.local/bin/ffmpeg-recorder
@@ -1,21 +1,31 @@
 #!/usr/bin/env bash
 
 ## Record Screen and Audio with ffmpeg with support for intel and nvidia gpu encoding 
-# Dependencies: ffmpeg, xdpyinfo, awk, pactl, lspci, pacman, zenity, ffmpegthumbnailer 
+# Dependencies: ffmpeg, xdpyinfo, awk, grep, pactl, lspci, vainfo, zenity, ffmpegthumbnailer 
 #				notify-send, slop, pkill, polybar-msg
 
+# Define directory and file extension based on what needs to be recorded
+ffmpeg_lock="/tmp/ffmpeg-recorder.lock"
+ffmpeg_lock_slop="/tmp/ffmpeg-recorder-slop.lock"
+ffmpeg_lock_audio="/tmp/ffmpeg-recorder-audio.lock"
+
+if [[ "$@" == "--audio" ]] || [[ -e "$ffmpeg_lock_audio" ]]; then 
+	file_type="m4a"
+	dir="$HOME/Videos/Recordings/Audio"
+else
+	file_type="mp4"
+	dir="$HOME/Videos/Recordings"
+fi
+
 # Get current timestamp
-time=$(date +%Y-%m-%d-%H-%M-%S)
+time="$(date +%Y-%m-%d-%H-%M-%S)"
+
+# Get segment number for generating filenames
+segment_number="$(cat $ffmpeg_lock 2>/dev/null | wc -l)" 
+file="recording_${time}_segment_${segment_number}.$file_type"
 
 # Get screen dimensions
 screen=$(xdpyinfo | awk '/dimensions/{print $2}')
-
-# Define directory and file names
-dir="$HOME/Videos/Recordings"
-file="recording_${time}.mp4"
-ffmpeg_lock="/tmp/ffmpeg-recorder.lock"
-ffmpeg_lock_slop="/tmp/ffmpeg-recorder-slop.lock"
-ffmpeg_lock_noaudio="/tmp/ffmpeg-recorder-noaudio.lock"
 
 # Get default audio sink and source
 audio_sink=$(pactl info | grep 'Default Sink' | awk '{print $3}')
@@ -24,12 +34,14 @@ audio_source=$(pactl info | grep 'Default Source' | awk '{print $3}')
 # Set frames per second for recording
 fps="60"
 
+# Set the logging level for ffmpeg to reduce clutter
 ffmpeg_command=(ffmpeg -hide_banner -loglevel error)
 
 # Set configurations based on available hardware
 if lspci | grep -q NVIDIA; then 
     config="-c:v h264_nvenc -preset p7"
-elif pacman -Q intel-media-driver &> /dev/null || pacman -Q libva-intel-driver &> /dev/null; then
+elif vainfo 2>&1 | grep -q "Driver version"; then
+    echo "VAAPI is supported. Desired output found."    
     config="-vaapi_device /dev/dri/renderD128 -vcodec h264_vaapi -vf format=nv12|vaapi,hwupload -crf 23 -pix_fmt rgb24"
 else
     config='-c:v libx264 -preset superfast -crf 23 -pix_fmt rgb24'
@@ -43,28 +55,11 @@ elif [[ -e "$ffmpeg_lock" ]]; then
 else
     status="off"
 fi
+
 # Create directory if it doesn't exist
 if [[ ! -d "$dir" ]]; then
 	mkdir -p "$dir"
 fi
-
-# Function to notify user about recording status
-notify_user() {
-	if [[ -e "$1" ]]; then
-		local file_name="${1##*/}"
-		zenity --question --title="Rename Recording" --text="Do you want to rename the recorded file?" &&
-	    new_filename=$(zenity --entry --title="Rename Recording" --text="Enter a new filename")
-	        if [[ -n "$new_filename" ]]; then
-	            # Rename the file if a new filename is provided
-	            mv "${dir}/$file_name" "${dir}/${new_filename}.mp4"
-	            local file_name="${new_filename}.mp4"
-	        fi
-	    ffmpegthumbnailer -i "${dir}/$file_name" -o /tmp/"$file_name".jpg -s 500
-		notify-send -a "Recorder" -u low -r 699 "Screen Recording Saved" -i /tmp/"$file_name".jpg
-	else
-		notify-send -a "Recorder" -u low -r 699 "Recording Canceled"
-	fi
-}
 
 # Function for countdown before starting recording
 countdown() {
@@ -74,57 +69,75 @@ countdown() {
 	done
 }
 
-# Get segment number for generating filenames
-segment_number="$(cat $ffmpeg_lock 2>/dev/null | wc -l)" 
-
-# Function to generate filename for recording segments
-generate_filename() {
-    echo "recording_${time}_segment_${segment_number}.mp4"
+# Function to notify user about recording status
+notify_user() {
+	if [[ -e "$1" ]]; then
+		local file_name="${1##*/}"
+		zenity --question --title="Rename Recording" --text="Do you want to rename the recorded file?" &&
+	    new_filename=$(zenity --entry --title="Rename Recording" --text="Enter a new filename")
+	        if [[ -n "$new_filename" ]]; then
+	            # Rename the file if a new filename is provided
+	            mv "${dir}/$file_name" "${dir}/${new_filename}"
+	            local file_name="${new_filename}.mp4"
+	        fi
+	    ffmpegthumbnailer -i "${dir}/$file_name" -o /tmp/"$file_name".jpg -s 500
+		dunst_action=$(notify-send -a "Recorder" -u low -r 699 "Recording Saved" -i /tmp/"$file_name".jpg \
+		--action="default,Reply" "Click to open")
+	
+		case "$dunst_action" in
+		"default" | "0")
+		    exo-open "$1"
+		    ;;
+		"2")
+		    exit 0
+		    ;;
+		esac
+	else
+		notify-send -a "Recorder" -u low -r 699 "Recording Canceled"
+	fi	
 }
 
-# Function to check ffmpeg execution status and handle errors
-check_ffmpeg_status() {
-    if [[ "$?" -ne 255 ]]; then
-        echo "Error: ffmpeg execution failed. Stopping the script."
-        cancel_recording
-        exit 1
-    elif [[ "$?" -eq 0 ]] || [[ "$?" -eq 1 ]]; then
-		stop_recording
-    fi
+# Function to cancel the recording if ffmpeg fails to record
+catch_error(){
+	exit_code="$?"
+	if [[ "$exit_code" == 255 ]]; then
+		echo "$exit_code"
+	else
+		echo "exit_code"
+		cancel_recording
+	fi
 }
 
 # Function to capture screen recording with or without audio
 record_screen() {
 	if [[ "$status" == "on" ]]; then echo "Already Recording" ;exit 0 ;fi
-	
-	file=$(generate_filename)
-	
+		
 	signal_start
-
+	
 	if [[ "$1" == "noaudio" ]]; then
-		"${ffmpeg_command[@]}" -f x11grab -video_size "$screen" -framerate "$fps" -i :0.0 -thread_queue_size 4096 \
+		"${ffmpeg_command[@]}" -f x11grab -framerate "$fps" -video_size "$screen" -i :0.0 -thread_queue_size 4096 \
 		$(echo $config) ${dir}/${file}
 	else
-		"${ffmpeg_command[@]}" -f x11grab -video_size "$screen" -framerate "$fps" -i :0.0 -thread_queue_size 4096 \
+		"${ffmpeg_command[@]}" -f x11grab -framerate "$fps" -video_size "$screen" -i :0.0 -thread_queue_size 4096 \
 		-f pulse -thread_queue_size 4096 -i ${audio_sink}.monitor \
         -f pulse -thread_queue_size 4096 -i ${audio_source} \
 		-filter_complex "[1:a][2:a]amerge=inputs=2[out]" \
 		-map 0:v -map "[out]" -map 1:a -map 2:a -c:a aac -b:a 192k -ac 2 \
 		$(echo $config) ${dir}/${file}
 	fi
-	check_ffmpeg_status  # Check ffmpeg execution status after the command
+		
+	catch_error # Check ffmpeg execution status after the command
 }
 
 # Function to capture area recording with or without audios
 record_area() {
 	if [[ "$status" == "on" ]]; then echo "Already Recording" ;exit 0 ;fi
-	file=$(generate_filename)
-	
-	# Get area for area recording
+
+	# Get area for area recording using slop
 	if [[ -e "$ffmpeg_lock_slop" ]]; then
 		read -r X Y W H G ID < <(cat "$ffmpeg_lock_slop")
 	else
-		get_win_data=$(slop -b 3 -f "%x %y %w %h %g %i")
+		get_win_data=$(slop -f "%x %y %w %h %g %i")
 		if [[ -z "$get_win_data" ]]; then 
 			cancel_recording
 			exit 0
@@ -137,91 +150,59 @@ record_area() {
 	signal_start
 	
 	if [[ "$1" == "noaudio" ]]; then
-		touch "$ffmpeg_lock_noaudio"
-		"${ffmpeg_command[@]}" -f x11grab -video_size ${W}x${H} -framerate "$fps" -i :0.0+${X},${Y} -thread_queue_size 4096 \
+		"${ffmpeg_command[@]}" -f x11grab -framerate "$fps" -video_size ${W}x${H} -i :0.0+${X},${Y} -thread_queue_size 4096 \
 		$(echo $config) ${dir}/${file}
 	else
-		"${ffmpeg_command[@]}" -f x11grab -video_size ${W}x${H} -framerate "$fps" -i :0.0+${X},${Y} -thread_queue_size 4096 \
+		"${ffmpeg_command[@]}" -f x11grab -framerate "$fps" -video_size ${W}x${H} -i :0.0+${X},${Y} -thread_queue_size 4096 \
 		-f pulse -thread_queue_size 4096 -i ${audio_sink}.monitor \
         -f pulse -thread_queue_size 4096 -i ${audio_source} \
 		-filter_complex "[1:a][2:a]amerge=inputs=2[out]" \
 		-map 0:v -map "[out]" -map 1:a -map 2:a -c:a aac -b:a 192k -ac 2 \
 		$(echo $config) ${dir}/${file}
 	fi
-	check_ffmpeg_status  # Check ffmpeg execution status after the command
+	
+	catch_error  # Check ffmpeg execution status after the command
 }
 
 # Function to capture audio only
 record_audio() {
 	if [[ "$status" == "on" ]]; then echo "Already Recording" ;exit 0 ;fi
-	file=$(generate_filename)
-
-	mkdir -p "$dir/Audio"
+	touch "$ffmpeg_lock_audio"
+		
+	signal_start
 	
-	"${ffmpeg_command[@]}" -f pulse -i ${audio_sink}.monitor -f pulse -i ${audio_source} \
+	ffmpeg -f pulse -i ${audio_sink}.monitor -f pulse -i ${audio_source} \
 	-filter_complex "[1:a][0:a]amerge=inputs=2[out]" \
-	-map "[out]" -c:a aac -b:a 256k ${dir}/Audio/${file%.*}.aac
+	-map "[out]" -map 0:a -map 1:a -c:a aac -b:a 256k \
+	${dir}/${file}
+	
+	catch_error # Check ffmpeg execution status after the command
 }
 
 # Function to stop ongoing recording and merge segments
 toggle_recording() {
-    if [[ -e "$ffmpeg_lock" ]]; then
-		if [[ "$status" == "on" ]]; then
-			# Pause recording
-	        pkill ffmpeg
-	        polybar-msg action "#recorder.hook.2"
-		else
-	        # Resume recording
-	        ((segment_number++))
-	   		file=$(generate_filename)
-	   		polybar-msg action "#recorder.hook.1"
-	   		if [[ -e "$ffmpeg_lock_slop" ]]; then
-				if [[ -e "$ffmpeg_lock_noaudio" ]]; then 
-					record_area noaudio &
-				else
-					record_area &
-				fi
-	   		else
-				if [[ -e "$ffmpeg_lock_noaudio" ]]; then 
-					record_screen noaudio &
-				else
-					record_screen &
-				fi
-			fi
-			echo "file '${dir}/${file}'" >> "$ffmpeg_lock"	
-        fi
-    else
-		"$0" --screen
-    fi
-}
+    if [[ ! -e "$ffmpeg_lock" ]]; then exit 0 ;fi
+	
+	if [[ "$status" == "on" ]]; then
+		# Pause recording
+        pkill ffmpeg
+        polybar-msg action "#recorder.hook.2"
+	else
+        # Resume recording
+   		polybar-msg action "#recorder.hook.1"
+   		if [[ -e "$ffmpeg_lock_slop" ]]; then
+			record_area &
+   		else
+			record_screen &
+		fi
+	fi
 
-# Function to stop ongoing recording and merge segments
-stop_recording() {
-    #if [[ "$status" == "off" ]]; then exit 0 ;fi
-    pkill ffmpeg
-    sleep 0.05
-    # Merge all segments into a single file
-	merged_file="$(awk -F"'" 'NR==1 {gsub("_segment_0", "", $2); print $2}' "$ffmpeg_lock")"
-	"${ffmpeg_command[@]}" -y -f concat -safe 0 -i "$ffmpeg_lock" -c copy "${merged_file}"
-	# Remove individual segment files
-	rm "${dir}/recording_"*"_segment_"*.*
-    signal_stop
-    notify_user "$merged_file"
-}
-
-# Function to cancel ongoing recording
-cancel_recording() {
-	pkill -9 ffmpeg 
-	rm "${dir}/recording_"*"_segment_"*.*
-	signal_stop
-	notify_user
 }
 
 # Function to signal the start of recording
 signal_start(){
-	file=$(generate_filename)
 	polybar-msg action "#recorder.hook.1"
-	echo "file '${dir}/${file}'" > "$ffmpeg_lock"
+	echo "file '${dir}/${file}'" >> "$ffmpeg_lock"
 }
 
 # Function to signal the stop of recording
@@ -230,9 +211,31 @@ signal_stop(){
 	rm /tmp/ffmpeg-recorder*
 }
 
+stop_recording(){
+	if [[ ! -e "$ffmpeg_lock" ]]; then exit 1 ;fi
+	pkill ffmpeg
+	sleep 0.05
+	# Merge all segments into a single file
+	merged_file="$(awk -F"'" 'NR==1 {gsub("_segment_0", "", $2); print $2}' "$ffmpeg_lock")"
+	"${ffmpeg_command[@]}" -y -f concat -safe 0 -i "$ffmpeg_lock" -c copy -map 0:v? -map 0:a? "${merged_file}"
+	# Remove individual segment files
+	rm "${dir}/recording_"*"_segment_"*.*
+	signal_stop
+	notify_user "$merged_file"
+}
+
+# Function to cancel ongoing recording
+cancel_recording() {
+	if [[ ! -e "$ffmpeg_lock" ]]; then exit 1 ;fi
+	pkill -9 ffmpeg
+	rm "${dir}/recording_"*"_segment_"*.*
+	signal_stop
+	notify_user
+}
+
 # Help section
 show_help() {
-    echo "Usage: ${0##*/} [ --option ]"
+    echo "Usage: ${0##*/} [ ]"
     echo "Options:"
     echo "  --screen        Start screen recording"
     echo "  --area          Start area recording"
@@ -246,30 +249,40 @@ show_help() {
 # Command-line argument handling
 case "$1" in
     "--status")
-        echo "$status" ;;
+        echo "$status"
+        ;;
     "--screen")
-        countdown '3'
-        record_screen ;;
+        countdown '2'
+        record_screen
+        ;;
     "--area")
-        record_area ;;
+        record_area
+        ;;
     "--screen-na")
-        countdown '3'
-        record_screen noaudio ;;
+        countdown '2'
+        record_screen noaudio
+        ;;
     "--area-na")
-        record_area noaudio ;;
+        record_area noaudio
+        ;;
     "--cancel")
-        cancel_recording ;;
+        cancel_recording
+        ;;
     "--toggle")
-        toggle_recording ;;
+        toggle_recording
+        ;;
     "--stop")
-        stop_recording ;;
+        stop_recording
+        ;;
     "--audio")
-        record_audio & signal_start ;;
+        record_audio
+        ;;
     "--help" | "-h" | "")
-        show_help ;;
+        show_help
+        ;;
     *)
         echo "Invalid option. Use --help for usage instructions."
         exit 1 ;;
-esac
+esac &
 
 exit 0
