Update mov

diff --git a/bin/.local/bin/mov b/bin/.local/bin/mov
--- a/bin/.local/bin/mov
+++ b/bin/.local/bin/mov
@@ -1,240 +1,204 @@
 #!/bin/sh
 
-version="2.0.2"
-base="https://www5.himovies.to"
-history_file="$HOME/.cache/lobster_history.txt"
-config_file="$HOME/.config/lobster/lobster_config.txt"
-[ ! -d "$HOME/.config/lobster" ] && mkdir -p "$HOME/.config/lobster"
-[ ! -f "$config_file" ] && printf "player=mpv\nsubs_language=English\n" > "$config_file"
-player="$(grep '^player=' "$config_file"|cut -d'=' -f2)" || player="mpv"
-subs_language="$(grep '^subs_language=' "$config_file"|cut -d'=' -f2)" || subs_language="English"
+c_red="\033[1;31m"
+c_green="\033[1;32m"
+c_yellow="\033[1;33m"
+c_blue="\033[1;34m"
+c_magenta="\033[1;35m"
+c_cyan="\033[1;36m"
+c_reset="\033[0m"
 
-yoinkity_yoink() {
-  key=$(curl -s "$movie_page"|sed -nE "s@.*recaptcha_site_key = '(.*)'.*@\1@p")
-  co=$(printf "https://www5.himovies.to:443"|base64|tr "=" ".")
-  vtoken=$(curl -s "https://www.google.com/recaptcha/api.js?render=$key"|
-    sed -nE "s_.*po\.src=.*releases/(.*)/recaptcha.*_\1_p")
-  recaptcha_token=$(curl -s "https://www.google.com/recaptcha/api2/anchor?ar=1&hl=en&size=invisible&cb=cs3&k=${key}&co=${co}&v=${vtoken}"|
-    sed -En 's_.*id="recaptcha-token" value="([^"]*)".*_\1_p')
-  id=$(curl -s "https://www5.himovies.to/ajax/get_link/${provider_id}?_token=${recaptcha_token}"|
-    sed -nE 's_.*"link":".*/(.*)\?z=".*_\1_p')
-
-  xml_links=$(curl -s "https://mzzcloud.life/ajax/embed-4/getSources?id=${id}" \
-    -H 'X-Requested-With: XMLHttpRequest'|tr '{|}' '\n'|
-    sed -nE 's_.*file":"([^"]*)","type.*_\1_p; s_.*file":"([^"]*)","label":"'$subs_language'.*".*_\1_p')
-  mpv_link=$(printf "%s" "$xml_links"|head -1)
-  subs_links=$(printf "%s" "$xml_links"|sed -n '2,$p'|sed -e 's/:/\\:/g' -e 'H;1h;$!d;x;y/\n/:/' -e 's/:$//')
-  [ -z "$mpv_link" ] && printf "No links found\n" && exit 1
-  [ -z "$subs_links" ] && printf "No subtitles found\n"
+help_text () {
+        while IFS= read -r line; do
+	    printf "%s\n" "$line"
+	done <<-EOF
+	Usage:
+	    ${0##*/} [-d | -p <download_dir>] [<query>]
+	    ${0##*/} [-v] [<query>]
+	    ${0##*/} [-t] [<query>]
+	    ${0##*/} -h
+	
+	Options:
+	    -h show help-text
+	    -d download video
+	    -t search tv-show (default search:movies)
+	    -p download video to specified directory
+	    -v use VLC as the media player
+	EOF
 }
 
-main() {
-  case "$media_type" in
-    movie)
-      if [ -z "$movie_page" ]; then
-        movie_page="$base"$(curl -s "https://www5.himovies.to/ajax/movie/episodes/${movie_id}"|
-          tr -d "\n"|sed -nE 's_.*href="([^"]*)".*UpCloud.*_\1_p')
-        provider_id=$(printf "%s" "$movie_page"|sed -nE "s_.*\.([0-9]*)\$_\1_p")
-        [ -z "$provider_id" ] && movie_page="$base"$(curl -s "https://www5.himovies.to/ajax/movie/episodes/${movie_id}"|
-          tr -d "\n"|sed -nE 's_.*href="([^"]*)".*Vidcloud.*_\1_p') && provider_id=$(printf "%s" "$movie_page"|
-          sed -nE "s_.*\.([0-9]*)\$_\1_p")
-      fi
-    yoinkity_yoink
-      case $player in
-        iina)
-          iina --no-stdin --keep-running --mpv-sub-files="$subs_links" --mpv-force-media-title="$movie_title" "$mpv_link" ;;
-        vlc)
-          if uname -a | grep -qE '[Aa]ndroid';then
-            am start --user 0 -a android.intent.action.VIEW -d "$mpv_link" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$movie_title" > /dev/null 2>&1 &
-          else
-            vlc "$mpv_link" --meta-title "$movie_title"
-          fi ;;
-        *)
-          if uname -a | grep -qE '[Aa]ndroid';then
-            am start --user 0 -a android.intent.action.VIEW -d "$mpv_link" -n is.xyz.mpv/.MPVActivity > /dev/null 2>&1 &
-          else
-            [ -z "$resume_from" ] && opts="" || opts="--start=${resume_from}%"
-            printf "Loading %s...\n" "$movie_title"
-            stopped_at=$(mpv "$opts" --sub-files="$subs_links" --force-media-title="$movie_title" "$mpv_link" 2>&1|grep AV|
-              tail -n1|sed -nE 's_.*AV: ([^ ]*) / ([^ ]*) \(([0-9]*)%\).*_\3_p')
-          fi ;;
-      esac 
-      # shellcheck disable=SC2034,SC2162
-      printf "Press Enter to save movie progress or Ctrl-C to exit (this will not reset your progress)\n" && read useless
-      if [ "$stopped_at" -gt 85 ]; then
-        if [ "$(grep -c "$movie_page" < "$history_file")" -eq 1 ]; then
-          rm "$history_file"
-        else
-          grep -sv "$movie_page" "$history_file" > "$history_file.tmp" && mv "$history_file.tmp" "$history_file"
-        fi
-      else
-        grep -sv "$movie_page" "$history_file" > "$history_file.tmp"
-        printf "%s\t%s\t%s\n" "$movie_page" "$stopped_at" "$movie_title" >> "$history_file.tmp"
-        mv "$history_file.tmp" "$history_file"
-      fi
-      exit 0 ;;
-    tv)
-      if [ -z "$season_id" ] || [ -z "$episode_id" ]; then
-        seasons_ids=$(curl -s "https://www5.himovies.to/ajax/v2/tv/seasons/${movie_id}"|
-          sed -nE 's_.*data-id="([0-9]*)".*_\1_p')
-        number_of_seasons=$(( $(printf "%s" "$seasons_ids"|wc -l|tr -d "[:space:]") + 1 ))
-        [ "$number_of_seasons" -gt 1 ] && printf "Please choose a season number between 1 and %s: " \
-          "$number_of_seasons" && read -r season_number || season_number=1
-        [ -z "$season_number" ] && season_number=$number_of_seasons
-        season_id=$(printf "%s" "$seasons_ids"|sed -nE "${season_number}p")
-        episode_ids=$(curl -s "https://www5.himovies.to/ajax/v2/season/episodes/${season_id}"|
-          sed -nE 's_.*data-id="([0-9]*)".*_\1_p')
-        number_of_episodes=$(( $(printf "%s" "$episode_ids"|wc -l|tr -d "[:space:]") + 1 ))
-        printf "Please choose an episode number between 1 and %s: " "$number_of_episodes" && read -r episode_number
-        [ -z "$episode_number" ] && episode_number=$number_of_episodes
-        episode_id=$(printf "%s" "$episode_ids"|sed -nE "${episode_number}p")
-      fi
-      [ -z "$movies_choice" ] || show_base=$(printf "%s" "$movies_choice"|cut -f1)
-      movie_page="${base}${show_base}\."$(curl -s "https://www5.himovies.to/ajax/v2/episode/servers/${episode_id}"|
-        tr -d "\n"|sed -nE 's_.*data-id="([0-9]*)".*title="Server UpCloud".*_\1_p')
-      provider_id=$(printf "%s" "$movie_page"|sed -nE "s_.*\.([0-9]*)\$_\1_p")
-      yoinkity_yoink
-      case $player in
-        iina)
-          iina --no-stdin --keep-running --mpv-sub-files="$subs_links" \
-            --mpv-force-media-title="${movie_title}: S${season_number} Ep ${episode_number}" "$mpv_link" ;;
-        vlc)
-          if uname -a | grep -qE '[Aa]ndroid';then
-            am start --user 0 -a android.intent.action.VIEW -d "$mpv_link" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$movie_title" > /dev/null 2>&1 &
-          else
-            vlc "$mpv_link" --meta-title "$movie_title: S${season_number} Ep ${episode_number}"
-          fi ;;
-        *)
-          if uname -a | grep -qE '[Aa]ndroid';then
-            am start --user 0 -a android.intent.action.VIEW -d "$mpv_link" -n is.xyz.mpv/.MPVActivity > /dev/null 2>&1 &
-          else
-            [ -z "$resume_from" ] && opts="" || opts="--start=${resume_from}%"
-            printf "Loading %s...\n" "$movie_title: S${season_number} Ep ${episode_number}"
-            stopped_at=$(mpv "$opts" --sub-files="$subs_links" --force-media-title="$movie_title: S${season_number} Ep ${episode_number}" "$mpv_link" 2>&1|grep AV|
-              tail -n1|sed -nE 's_.*AV: ([^ ]*) / ([^ ]*) \(([0-9]*)%\).*_\3_p')
-          fi ;;
-      esac
-      # shellcheck disable=SC2034,SC2162
-      printf "Press Enter to save episode progress or Ctrl-C to exit (this will not reset your progress)\n" && read useless
-      if [ "$stopped_at" -gt 85 ]; then
-        episode_id=$(curl -s "https://www5.himovies.to/ajax/v2/season/episodes/${season_id}"|
-          grep 'data-id'|sed -nE "/data-id=\"${episode_id}\"/{n;p;}"|sed -nE 's/.*data-id="([0-9]*)".*/\1/p')
-        movie_id=$(printf "%s" "$selection"|sed -nE 's_.*-([0-9]*).*_\1_p')
-        stopped_at=0 && episode_number=$(( episode_number + 1 ))
-          if [ -z "$episode_id" ]; then
-            season_id=$(curl -s "https://www5.himovies.to/ajax/v2/tv/seasons/${movie_id}"|
-              grep 'data-id'|sed -nE "/data-id=\"${season_id}\"/{n;p;}"|sed -nE 's/^.*data-id="([0-9]*)".*/\1/p')
-            episode_id=$(curl -s "https://www5.himovies.to/ajax/v2/season/episodes/${season_id}"|
-              grep -m1 data-id|sed -nE 's_.*data-id="([0-9]*)".*_\1_p')
-            season_number=$(( season_number + 1 ))
-            episode_number=1
-            [ -z "$show_base" ] || show_base=$(printf "%s" "$show_base"|cut -f1)
-            if [ -z "$episode_id" ] && [ "$(wc -l < "$history_file")" -lt 2 ]; then
-              rm "$history_file" && exit 0
-            fi
-          fi
-      fi 
-      grep -sv "$show_base" "$history_file" > "$history_file.tmp"
-      printf "%s\t%s\t%s\t%s\t%s: S%s Ep(%s)\n" "$show_base" "$season_id" \
-        "$episode_id" "$stopped_at" "$movie_title" "$season_number" "$episode_number" >> "$history_file.tmp"
-      mv "$history_file.tmp" "$history_file"
-      ;;
-    *)
-      exit 1 ;;
-  esac
-  # shellcheck disable=SC2034,SC2162
-  tput clear && printf "Press Enter to continue watching, or Ctrl+C to exit" && read -r useless
-  first_run="" && play_from_history
+err () { 
+    printf "$c_red%s$c_reset\n" "$*" >&2 
 }
 
-get_input() {
-  if [ -z "$deez" ]; then
-    [ -z "$*" ] && printf "Enter a Movie/TV Show name: " && read -r query || query=$*
-    query=$(printf "%s" "$query"|tr " " "-")
-    search_params=search/${query}
-  else
-    search_params=$deez
-  fi
-  movies_results=$(curl -s "${base}/${search_params}"|
-    sed -nE '/class="film-name"/ {n; s/.*href="(.*)".*/\1/p;n; s/.*title="(.*)".*/\1/p;d;}'|
-    sed -e 'N;s/\n/\{/' -e "s/&#39;/'/g")
-  movies_choice=$(printf "%s" "$movies_results"|sed -nE 's_/(.*)/(.*)\{(.*)_\2{\3 (\1)_p'|
-    fzf --border -1 --reverse --height=12 -d"{" --with-nth 2..|sed -nE "s_(.*)\{(.*) \((.*)\)_/\3/\1\t\2_p")
-
-  movie_id=$(printf "%s" "$movies_choice"|cut -f1|sed -nE 's_.*/[movie/|tv/].*-([0-9]*).*_\1_p')
-  movie_title=$(printf "%s" "$movies_choice"|cut -f2)
-  media_type=$(printf "%s" "$movies_choice"|sed -nE 's_.*/([^/]*)/.*_\1_p')
+get_query () {
+	if [ -z "$*" ]; then
+		[ "$is_show" -eq "0" ] && printf "Search Movie: " || printf "Search TV-show: "
+		read -r movie
+	else
+		movie=$*
+	fi
+	query=$(printf "%s" "$movie" | tr " " "+")
 }
 
-play_from_history() {
-  selection=$(fzf --border --reverse --tac -1 --cycle --height=12 -d"\t" --with-nth -1 < "$history_file")
-  [ -z "$selection" ] && exit 0
-  if printf "%s" "$selection"|grep -qE '/watch-movie/';then
-    media_type="movie"
-    movie_page=$(printf "%s" "$selection"|cut -f1)
-    provider_id=$(printf "%s" "$movie_page"|sed -nE "s_.*\.([0-9]*)\$_\1_p")
-    resume_from=$(printf "%s" "$selection"|cut -f2)
-    movie_title=$(printf "%s" "$selection"|cut -f3)
-  else
-    media_type="tv"
-    show_base=$(printf "%s" "$selection"|cut -f1)
-    season_id=$(printf "%s" "$selection"|cut  -f2)
-    episode_id=$(printf "%s" "$selection"|cut -f3)
-    resume_from=$(printf "%s" "$selection"|cut -f4)
-    [ "$resume_from" -eq -1 ] && resume_from=0
-    movie_title=$(printf "%s" "$selection"|cut -f5|sed -nE 's_(.*): S[0-9].*_\1_p')
-    season_number=$(printf "%s" "$selection"|cut -f5|sed -nE 's_.*: S([0-9]*).*_\1_p')
-    episode_number=$(printf "%s" "$selection"|cut -f5|sed -nE 's_.*S[0-9].*Ep\(([0-9]*)\).*_\1_p')
-  fi
-  continue_history=true
-  if [ -z "$first_run" ]; then
-    main
-  else
-    first_run=false
-  fi
+get_token() {
+	printf "${c_blue}Fetching token.."
+	token=$(curl -X POST -sc - -o /dev/null "$base_url:5679/authorization/session/continue?contentUsageType=Viewing" -A "uwu" -H "Origin: $base_url" -e "$base_url" | sed -n 's/.*ipiid\t//p')
 }
 
-while getopts "cduUvVht" opt; do
-  case $opt in
-    c) play_from_history ;;
-    d)
-      rm -f "$history_file" && printf "History file deleted\n" && exit 0 ;;
-    u|U)
-      update=$(curl -s "https://raw.githubusercontent.com/justchokingaround/lobster/master/lobster.sh"||die "Connection error")
-      update="$(printf '%s\n' "$update" | diff -u "$(which lobster)" -)"
-      if [ -z "$update" ]; then
-        printf "Script is up to date :)\n"
-      else
-        if printf '%s\n' "$update" | patch "$(which lobster)" - ; then
-          printf "Script has been updated\n"
-        else
-          printf "Can't update for some reason!\n"
-        fi
-      fi
-      exit 0 ;;
-    v|V)
-      printf "Lobster version: %s\n" "$version" && exit 0 ;;
-    t)
-      printf "What do you want to watch? (T)V Show or (M)Movie: " && read -r media_type
-      [ "$media_type" = "T" ] || [ "$media_type" = "t" ] && deez="tv-show" || deez="movie"
-      get_input && main && exit 0 ;;
-    h)
-      printf "Usage: lobster [arg] \n"
-      printf "Play movies and TV shows from himovies.to\n"
-      printf "  -c, \t\tContinue watching from last minute saved\n"
-      printf "  -d, \t\tDelete history file\n"
-      printf "  -u, \t\tUpdate script\n"
-      printf "  -v, \t\tPrint version\n"
-      printf "  -t, \t\tSuggest a trending TV Show or Movie\n"
-      printf "  -h, \t\tDisplay this help and exit\n"
-      exit 0 ;;
-    \?)
-      printf "Invalid option: -%s\n" "$OPTARG" >&2
-      exit 1 ;;
-  esac
+input() {
+	printf "$c_yellow  $1??(1-%s):$c_reset " "$2"
+	read -r x
+	while [ -z "$x" ] || ! [ "$x" -eq "$x" ] 2>/dev/null || [ "$x" -lt "1" ] || [ "$x" -gt "$2" ];do
+	    err "Invalid choice"
+	    printf "$c_yellow  $1??(1-%s):$c_reset " "$2"
+	    read -r x
+	done
+	[ "$3" -eq "0" ] && season_choice=$x || ep_no=$x 
+	unset x
+}
+
+stream () {
+	case $player_fn in 
+		vlc)
+			setsid -f "$player_fn" --http-referrer="$base_url" "$1" > /dev/null 2>&1;;
+		mpv)
+			setsid -f "$player_fn" "$1" --referrer="$base_url" --force-media-title="$2" > /dev/null 2>&1;;
+	esac
+}
+
+download () {
+	printf "${c_blue}Downloading %s${c_reset}\n" "$2"
+	aria2c --summary-interval=0 -x 16 -s 16 --referer="$base_url" "$1" --dir="$download_dir" -o "${2}.mp4" --download-result=hide
+}
+
+get_show() {
+	printf "\33[2K\r${c_blue}Searching query.."
+	data=$(curl -s "$base_url/tv-shows/trending?search=$query")
+	results=$(printf "%s" "$data" | sed "s/:\"$movie.*//" | tr '{|}' '\n' | sed -nE 's/.*"name":"([^"]*)","numberOfSeasons":(.*),.*numberOfEpisod.*"id":(.*),"available":true.*/\2 \3 \1/p')
+	[ -z "$results" ] && printf "\33[2K\r${c_red}No search results found${c_reset}" && exit 0
+	printf "\33[2K\r${c_green}Results found\n"
+	result=$(printf "%s" "$results" | fzf | tr "[:punct:]" " " | tr -s " " | tr ' |[:upper:]' '-|[:lower:]')
+	[ -z "$result" ] && err "No tv-show selected" && exit 0
+	printf "${c_magenta}selected $result\n${c_blue}Fetching season/episode list"
+	build_id=$(printf "%s" "$data" | sed -nE 's/.*buildId\":"(.*)",.*run.*/\1/p')
+	result_id=$(printf "%s" "$result" | cut -d"-" -f2-)
+	show_all=$(curl -s "$base_url:443/_next/data/$build_id/tv-show/$result_id/season-1/episode-1.json" -b "theflix.ipiid=$token" | sed 's/selectedTvSeason.*//' | tr '{|}' '\n')
+	printf "\33[2K\r${c_green}Seasons/Episodes list fetched\n"
+	get_show_se
+}
+
+get_show_se() {
+	season=$(printf "%s" "$result" | cut -d"-" -f1)
+	input "Season" "$season" "0"
+	noofeps=$(printf "%s" "$show_all" | sed -nE "s/\"name\":\".*$season_choice\",\"numberOfEpisodes\":(.*),\"seasonN.*/\1/p")
+	input "Episode" "$noofeps" "1"
+	get_ep_link "$season_choice" "$ep_no"
+}
+
+get_ep_link(){
+	tput clear
+	printf "${c_blue}Loading Episode $2"
+	id=$(printf "%s" "$show_all" | sed -nE "s/^\"episodeNumber\":$2,.*name.*\"seasonNumber\":$1,.*videos\":\[\"(.*)\"\]/\1/p")
+	display=$(printf "%s S%s E%s" "$(printf "$result_id" | cut -d"-" -f2- | tr "-" " ")" "$1" "$2")
+	[ -z "$id" ] && printf "\33[2K\r${c_red}Episode doesn't exist on this site${c_reset}" || play_link "tv"
+}
+
+get_movie () {
+	printf "\33[2K\r${c_blue}Searching query.."
+	results=$(curl -s "$base_url/movies/trending?search=$query" | sed "s/:\"$movie.*//" | tr '{|}' '\n' | sed -nE 's/^\"name\":"([^"]*)",.*available\":true.*videos\":\["(.*)"\],.*/\2\t\1/p')
+	[ -z "$results" ] && printf "\33[2K\r${c_red}No search results found${c_reset}" && exit 0
+	printf "\33[2K\r${c_green}Results found\n"
+	movie_name=$(printf "$results" | cut -f2- | fzf)
+	[ -z "$movie_name" ] && err "No movie chosen" && exit 0
+	tput clear
+	printf "${c_blue}Fetching movie"
+	display=$(printf "%s" "$movie_name" | tr -d '[:punct:]')
+	id=$(printf "%s" "$results" | sed -n "s/\t$movie_name$//p")
+	play_link "movies"
+}
+
+play_link() {
+	printf "\33[2K\r${c_blue}Fetching video link"
+	video_link="$(curl -s "$base_url:5679/$1/videos/$id/request-access?contentUsageType=Viewing" -b "theflix.ipiid=$token" | sed -nE 's/.*url\":"([^"]*)",.*id.*/\1/p')"
+	if [ -z "$video_link" ];then 
+	    printf "\33[2K\r${c_red}Video Url not found${c_reset}\n"
+	else
+	    printf "\33[2K\r${c_green}Video link fetched${c_reset}\n%s" "$video_link"
+	    if [ "$is_download" -eq "0" ];then
+		stream "$video_link" "$display"
+	    else
+		download "$video_link" "$display"
+	    fi
+	fi
+}
+
+trap "exit 0" INT HUP
+base_url="https://theflix.to"
+player_fn="mpv"
+is_show=0
+is_download=0
+download_dir=.
+
+while getopts 'dhtp:v' OPT; do
+        case $OPT in
+                d)
+                        is_download=1
+                        ;;
+                t)
+                        is_show=1
+                        ;;
+                p)
+                        is_download=1
+			download_dir=$OPTARG
+                        ;;
+                v)
+                        player_fn="vlc"
+                        ;;
+                *|h)
+                        help_text
+                        exit 0
+                        ;;
+	esac
 done
+shift $((OPTIND - 1))
 
-if [ -z "$continue_history" ]; then
-  get_input "$*"
-  main
-fi
+get_query "$*"
+get_token
+[ "$is_show" -eq "0" ] && get_movie || get_show
+
+while :; do
+        printf "\n${c_green}Currently playing %s\n" "$display"
+        printf "$c_blue(%s) %s$c_reset\n" "s" "search next"
+        [ "$is_show" -eq "1" ] && [ "$ep_no" != "$noofeps" ] && printf "$c_yellow(%s) %s$c_reset\n" "n" "next"
+        [ "$is_show" -eq "1" ] && [ "$ep_no" != "1" ] && printf "$c_cyan(%s) %s$c_reset\n" "p" "previous"
+        [ "$is_show" -eq "1" ] && printf "$c_green(%s) %s$c_reset\n" "c" "change season"
+        [ "$is_show" -eq "1" ] && printf "$c_blue(%s) %s$c_reset\n" "e" "select episode"
+	printf "$c_magenta(%s) %s$c_reset\n" "d" "download current video"
+	printf "$c_red(%s) %s$c_reset\n" "q" "exit"
+        printf "${c_green}Enter choice:$c_reset "
+        read -r choice
+        case $choice in
+                s)
+			get_query
+			[ "$is_show" -eq "0" ] && get_movie || get_show
+			;;
+                d)
+			download "$video_link" "$display";;
+                n)
+			ep_no=$((ep_no + 1))
+			[ "$ep_no" -gt "$noofeps" ] && err "Episode out of range" && ep_no=$((ep_no - 1)) || get_ep_link "$season_choice" "$ep_no";;
+                p)
+			ep_no=$((ep_no - 1))
+			[ "$ep_no" -lt "1" ] && err "Episode out of range" && ep_no=$((ep_no + 1)) || get_ep_link "$season_choice" "$ep_no";;
+                e)
+			input "Episode" "$noofeps" "1"
+                        get_ep_link "$season_choice" "$ep_no";;
+                c)
+			get_show_se;;
+                q)
+                        break;;
+                *)
+                        err "invalid choice";;
+        esac
+done
