Update rofi-media

diff --git a/bin/.local/bin/rofi-media b/bin/.local/bin/rofi-media
--- a/bin/.local/bin/rofi-media
+++ b/bin/.local/bin/rofi-media
@@ -103,7 +103,7 @@ process_media(){
 		notify-send -r 12 -u low -a rofi-media "rofi-media" "No files were found in $media_directory"
 		return
 	elif [[ ${#lines[@]} -gt "$(cut -f2 "$saved_lines" 2> /dev/null | wc -l)" ]]; then
-		notify-send -r 12 -u low -a rofi-media "rofi-media" "Getting posters..."
+		notify-send -r 12 -u low -a rofi-media "rofi-media" "Updating List..."
 	fi
 
 	# Declare an associative array
@@ -132,16 +132,13 @@ process_media(){
 			if [[ "$name" =~ ([1][9][0-9]{2}|20[0-9]{2}) ]]; then
 				# Get the year if present and strip the title of extra info
 				year="${BASH_REMATCH[1]}"
-				title=$(echo "$name" | sed -e "s/$year.*//" -e 's/\[[^]]*\]//g' -e 's/([^)]*)//g' -e 's/{[^}]*}//g' -e 's/[._()]/ /g' -e 's/[[:space:]]\+/ /g' -e 's/^[ \t]*//;s/[ \t]*$//' -e 's/ S[0-9][0-9]*.*//')
-
+				title=$(echo "$name" | sed -e "s/$year.*//" -e 's/^\[.*\] \(.*\) - .*/\1/' -e 's/\[[^]]*\]//g' -e 's/([^)]*)//g' -e 's/{[^}]*}//g' -e 's/[._()]/ /g' -e 's/[[:space:]]\+/ /g; s/^[ \t]*//; s/[ \t]*$//; s/ S[0-9][0-9]*.*//')
 				# Check if title is empty or only contains the year
-				if [[ -z "$title" || "$title" =~ ^[[:space:]]*$ ]]; then
-					# If title is empty or only contains spaces, set title to the year itself
-					title="$year"
-				fi
+				# If title is empty or only contains spaces, set title to the year itself
+				[[ -z "$title" || "$title" =~ ^[[:space:]]*$ ]] && title="$year"
 			else
 				# Remove trailing spaces
-				title=$(echo "$name" | sed -e 's/\[[^]]*\]//g' -e 's/([^)]*)//g' -e 's/{[^}]*}//g' -e 's/[._()]/ /g' -e 's/[[:space:]]\+/ /g' -e 's/^[ \t]*//;s/[ \t]*$//' -e 's/ S[0-9][0-9]*.*//')
+				title=$(echo "$name" | sed -e 's/^\[.*\] \(.*\) - .*/\1/' -e 's/\[[^]]*\]//g' -e 's/([^)]*)//g' -e 's/{[^}]*}//g' -e 's/[._()]/ /g' -e 's/[[:space:]]\+/ /g; s/^[ \t]*//; s/[ \t]*$//; s/ S[0-9][0-9]*.*//')
 				year=""
 			fi
 			printf "%s\t%s\n" "$line" "$title" >> "$saved_lines" 2> /dev/null
@@ -242,6 +239,8 @@ play_media() {
 		find -L "${file_path%/*}" -maxdepth 1 -type f \( -iname "*.mp4" -o -iname "*.mkv" \) | sort | awk -v start="$file_path" '$0 >= start' > "$playlist"
 		mpv "${player_cmd[@]}" "$playlist" >/dev/null 2>&1
 	fi
+
+	#[[ "$?" -ne 0 ]] && echo "Couldn't Open File!"; exit 1
 }
 
 save_history(){
@@ -289,7 +288,7 @@ prompt(){
   local selected_directory="$dir"
 
   get_next_episode
-
+	
 	if [[ -n "$next_episode_file" ]]; then
 		if [[ "$progress" -ge 90 ]]; then
 			options="$(prompt_menu "Next\nReplay\nSelect\nExit" "Select an option:")"
@@ -321,19 +320,7 @@ prompt(){
 			;;
 		esac
 	else
-		# Check if there is another season available
-		next_season_dir="$(echo "$season_dirs" | grep -FA1 "$selected_directory" | tail -n1)"
-		[[ -n "$next_season_dir"  && "$next_season_dir" != "$selected_directory" ]] && binge_next_season="$(prompt_menu "Yes\nNo" "Next season available. Play next season?")"
-	
-		if [[ "$binge_next_season" == "Yes"  && "$next_season_dir" != "$selected_directory" ]]; then
-			first_episode_file=$(ls -v "$next_season_dir" | grep -E '\.mp4$|\.mkv$' | head -n1)
-			if [[ -n "$first_episode_file" ]]; then
-				play_media "$next_season_dir/$first_episode_file"
-				grep -Fq "$next_season_dir" "$saved_lines" && show="$next_season_dir"
-				save_history "$show"
-				prompt "$show"
-			fi
-		fi
+		get_next_season
 	fi
 }
 
@@ -356,78 +343,20 @@ play_history(){
     next_episode_file=$(ls -v "$selected_directory" | grep -Ei "([sS][0-9]+[eE]$next_episode_number| - $next_episode_number - | - $next_episode_number[[:space:]]| - $next_episode_number[^a-zA-Z0-9]|[_\.x-]$next_episode_number[^a-zA-Z0-9])" | grep -E '\.mp4$|\.mkv$')
   }
 
-	if [[ "$progress" -ge 90 ]]; then    
-    get_next_episode
-		if [[ -n "$next_episode_file" ]]; then
-			file_path="$selected_directory/$next_episode_file"
-			position=""
-		else
-			file_path=""
+	get_next_season(){
+		# Check if there is another season available
+		next_season_dir="$(echo "$season_dirs" | grep -FA1 "$selected_directory" | tail -n1)"
+		[[ -n "$next_season_dir"  && "$next_season_dir" != "$selected_directory" ]] && binge_next_season="$(prompt_menu "Yes\nNo" "Next season available. Play next season?")"
+
+		if [[ "$binge_next_season" == "Yes"  && "$next_season_dir" != "$selected_directory" ]]; then
+			first_episode_file=$(ls -v "$next_season_dir" | grep -E '\.mp4$|\.mkv$' | head -n1)
+			if [[ -n "$first_episode_file" ]]; then
+				play_media "$next_season_dir/$first_episode_file"
+				grep -Fq "$next_season_dir" "$saved_lines" && show="$next_season_dir"
+				save_history "$show"
+				prompt "$show"
+			fi
 		fi
-	fi
-
-	[[ -n "$file_path" ]] && history=$(prompt_menu "Yes\nNo" "Resume from where you left off?")
-
-	if [[ "$history" == "Yes" ]]; then
-		if [[ -n $(echo "$show" | grep -F "$dir") ]]; then
-			show="$dir"
-		else
-			show="${dir%/*}"
-		fi
-
-		play_media "$file_path" "$position"
-		save_history "$show"
-		[[ -d "$show" ]] &&  prompt "$show"
-		exit 0
-	else
-		if [[ -f "$show" ]]; then
-			play_media "$show"
-			save_history "$show"
-		else
-			select_episode "$show"
-		fi
-	fi
-}
-
-select_episode(){
-	local show="$1"
-
-	list_seasons() {
-		season=$(prompt_menu "$(echo "$1" | sed -E '
-	    # Handle "S01P01" -> "Season 1: Part 1" (case-insensitive)
-	    s/.*[sS]0?([1-9][0-9]*)[pP]0?([1-9][0-9]*).*/Season \1: Part \2/; t;
-	    # Handle "Season 3 Part 1" -> "Season 3: Part 1"
-	    s/.*[sS]eason[[:space:]]+([0-9]+)[[:space:]]*-[[:space:]]*Part[[:space:]]+([0-9]+).*/Season \1: Part \2/; t;
-	    # Handle "Season 3 - Part 1" -> "Season 3: Part 1"
-	    s/.*[sS]eason[[:space:]]+([0-9]+)[[:space:]]*-[[:space:]]*Part[[:space:]]+([0-9]+).*/Season \1: Part \2/; t;
-	    # Handle "S01" -> "Season 1" (case-insensitive)
-	    s/.*[sS]0?([1-9][0-9]*).*/Season \1/; t;
-	    # Handle "Season 3" -> "Season 3" (case-insensitive)
-	    s/.*[sS]eason[[:space:]]+([0-9]+).*/Season \1/; t;
-	    # Handle cases with extra information, just keep the name unchanged
-	    s!.*/!!')" "Select the season:")
-	}
-
-	list_episodes() {
-		# Extract episode numbers and titles, and format the selection
-		episode_list="$(ls -vp "$1" | grep -v / | grep -E '\.mp4$|\.mkv$' | sed -E '
-		# Handle [group] tag and metadata in square brackets - ignore group name and metadata
-		s/\[.*\][[:space:]]+[^-]+[[:space:]]+-[[:space:]]+([0-9]+)[[:space:]]+\[.*\].*$/Episode \1/; t;
-		# Handle standard episode formats with season and episode numbers, capturing titles after SXXEXX
-		s/.*[sS][0-9]+[Ee]([0-9]+)[^A-Za-z0-9]*([^0-9]+\S[^0-9]+?)[. ]+[^.]+$/Episode \1: \2/; t;
-		s/.*[sS][0-9]+[Ee]([0-9]+)[^A-Za-z0-9]*([^0-9]+\S[^0-9]+?)[. ]+.*$/Episode \1: \2/; t;
-		s/.*[sS][0-9]+[Ee]([0-9]+).*$/Episode \1/; t;
-		# Match complex titles after a number if present, or just extract the title after the last dash
-		s/.* - ([0-9]+[^0-9a-zA-Z]?) - ([^0-9]+?)\..*$/Episode \1: \2/; t;
-		s/.* - ([^0-9]+?) - ([^0-9]+?)\..*$/\2/; t;
-		s/.* - ([0-9]+[^0-9a-zA-Z]?)\..*$/Episode \1/; t;
-		s/.* - Episode ([0-9]+) - ([^0-9]+?)\..*$/Episode \1: \2/; t;
-		s/.* - Episode ([0-9]+)\..*$/Episode \1/; t;
-		s/.*[sS][0-9]+[Ee]([0-9]+)\..*$/Episode \1/; t;
-		# Handle cases where title is complex and episode number is not in the format
-		s/.* - ([^-]+)\..*$/\1/; t;
-		# Fallback for movies or files without episode or season numbers
-		s/.* ([^\/]+)\..*$/\1/' | sed -E 's/\./ /g')"
 	}
 
 	# Check if there are multiple season directories, only if there are no video files in the directory
@@ -454,6 +383,88 @@ select_episode(){
 	elif [[ -z "$(find -L "$show" -maxdepth 1 -type f -iregex '.*\.\(mp4\|mkv\)')" && -z "$season_dirs" ]]; then
 		season_dirs="$(find -L "$show" -maxdepth 1 -mindepth 1 -type d | sort)"
 	fi
+
+	if [[ "$progress" -ge 90 ]]; then    
+    get_next_episode
+		if [[ -n "$next_episode_file" ]]; then
+			file_path="$selected_directory/$next_episode_file"
+			position=""
+		else
+			file_path=""
+			get_next_season
+			[[ "$binge_next_season" == "Yes" ]] && exit 0
+		fi
+	fi
+
+	[[ -n "$file_path" ]] && history=$(prompt_menu "Yes\nNo" "Resume from where you left off?")
+
+	if [[ "$history" == "Yes" ]]; then
+		if [[ -n $(echo "$show" | grep -F "$dir") ]]; then
+			show="$dir"
+		else
+			show="${dir%/*}"
+		fi
+
+		play_media "$file_path" "$position"
+		save_history "$show"
+		[[ -d "$show" ]] &&  prompt "$show"
+		exit 0
+	else
+		if [[ -f "$show" ]]; then
+			play_media "$show"
+			save_history "$show"
+		else
+			select_episode
+		fi
+	fi
+}
+
+select_episode(){
+
+	list_seasons() {
+		season=$(prompt_menu "$(echo "$1" | sed -E '
+    # Handle "S01P01" -> "Season 1: Part 1" (case-insensitive)
+    s/.*[sS]0?([1-9][0-9]*)[pP]0?([1-9][0-9]*).*/Season \1: Part \2/; t;
+    # Handle "Season 3 Part 1" -> "Season 3: Part 1"
+    s/.*[sS]eason[[:space:]]+([0-9]+)[[:space:]]*-[[:space:]]*Part[[:space:]]+([0-9]+).*/Season \1: Part \2/; t;
+    # Handle "Season 3 - Part 1" -> "Season 3: Part 1"
+    s/.*[sS]eason[[:space:]]+([0-9]+)[[:space:]]*-[[:space:]]*Part[[:space:]]+([0-9]+).*/Season \1: Part \2/; t;
+    # Handle "Episodes 001-148" -> "Episodes 001-148"
+    s/.*Episodes[[:space:]]+([0-9]+)-([0-9]+).*/Episodes \1-\2/; t;
+    # Handle "Movies" -> "Movies"
+    s/.*Movies.*/Movies/; t;
+    # Handle "S01" -> "Season 1" (case-insensitive)
+    s/.*[sS]0?([1-9][0-9]*).*/Season \1/; t;
+    # Handle "Season 3" -> "Season 3" (case-insensitive)
+    s/.*[sS]eason[[:space:]]+([0-9]+).*/Season \1/; t;
+    # Handle cases with extra information, just keep the name unchanged
+    s!.*/!!')" "Select the season:")
+
+	}
+
+	list_episodes() {
+		# Extract episode numbers and titles, and format the selection
+		 episode_list="$(ls -vp "$1" | grep -v / | grep -E '\.mp4$|\.mkv$' | sed -E '
+			# Handle [group] tag and metadata in square brackets - ignore group name and metadata
+			s/\[.*\][[:space:]]+[^-]+[[:space:]]+-[[:space:]]+([0-9]+)[[:space:]]+\[.*\].*$/Episode \1/; t;
+			# Handle standard episode formats with season and episode numbers, capturing titles after SXXEXX
+			s/.*[sS][0-9]+[Ee]([0-9]+)[^A-Za-z0-9]*([^0-9]+\S[^0-9]+?)[. ]+[^.]+$/Episode \1: \2/; t;
+			s/.*[sS][0-9]+[Ee]([0-9]+)[^A-Za-z0-9]*([^0-9]+\S[^0-9]+?)[. ]+.*$/Episode \1: \2/; t;
+			s/.*[sS][0-9]+[Ee]([0-9]+).*$/Episode \1/; t;
+			# Match complex titles after a number if present, or just extract the title after the last dash
+			s/.* - ([0-9]+[^0-9a-zA-Z]?) - ([^0-9]+?)\..*$/Episode \1: \2/; t;
+			s/.* - ([^0-9]+?) - ([^0-9]+?)\..*$/\2/; t;
+			s/.* - ([0-9]+[^0-9a-zA-Z]?)\..*$/Episode \1/; t;
+			s/.* - Episode ([0-9]+) - ([^0-9]+?)\..*$/Episode \1: \2/; t;
+			s/.* - Episode ([0-9]+)\..*$/Episode \1/; t;
+			s/.*[sS][0-9]+[Ee]([0-9]+)\..*$/Episode \1/; t;
+			# Handle movies or files with "The Movie" in the title
+			s/.*[[:space:]]+-[[:space:]]+The[[:space:]]+Movie[[:space:]]+-[[:space:]]+([^[]+)[[:space:]]+\[.*\].*$/\1/; t;
+			# Handle cases where title is complex and episode number is not in the format
+			s/.* - ([^-]+)\..*$/\1/; t;
+			# Fallback for movies or files without episode or season numbers
+			s/.* ([^\/]+)\..*$/\1/' | sed -E 's/\./ /g')"
+	}
 
 	if [[ -n "$season_dirs" ]]; then
 	  list_seasons "$season_dirs"
@@ -488,11 +499,11 @@ select_episode(){
 			fi
 		else
 			if [[ "$number_of_seasons" -eq 1 ]]; then
-				season_dir=$(ls -v "$show" | grep -E -i "$season" | head -n 1)
+				season_dir=$(ls -v "$show" | grep -Fi "$season" | head -n 1)
 				selected_directory="$show/$season_dir"
 				#echo 3
 			else
-				season_dir=$(echo "$season_dirs" | grep -E -i "$season" | head -n1)
+				season_dir=$(echo "$season_dirs" | grep -Fi "$season" | head -n1)
 				selected_directory="$season_dir"
 				if [[ -n $(echo "$show" | grep -F "$season_dir") ]]; then
 					show="$season_dir"
@@ -540,7 +551,7 @@ select_episode(){
 
 		if [[ -n "$episode_title" ]] && ! [[ $selection =~ "Ep" ]]; then
 			# Handle patterns with no episode number, matching by title
-			episode_file=$(ls -p "$selected_directory" | grep -i "$episode_title" | grep -E '\.mp4$|\.mkv$')
+			episode_file=$(ls -p "$selected_directory" | grep -Fi "$episode_title" | grep -E '\.mp4$|\.mkv$')
 		else
 			# Handle both patterns with episode number
 			episode_file=$(ls -p "$selected_directory" | grep -Ei "([sS][0-9]+[eE]$episode_number| - Episode $episode_number - .*| - Episode $episode_number\..*| - $episode_number[[:space:]]| - $episode_number[^a-zA-Z0-9]|[_\.x-]$episode_number[^a-zA-Z0-9])" | grep -E '\.mp4$|\.mkv$')
@@ -570,6 +581,10 @@ while [[ $# -gt 0 ]]; do
 			;;
 		--clear)
 			[[ -f "$media_history" ]] && rm "$media_history" && echo "History Cleared!"
+			shift # Move to next argument
+			;;
+		--fix)
+			rm "$data_dir"/*/*.txt
 			shift # Move to next argument
 			;;
 		--edit|-e)
