Update rofi-media

diff --git a/bin/.local/bin/rofi-media b/bin/.local/bin/rofi-media
--- a/bin/.local/bin/rofi-media
+++ b/bin/.local/bin/rofi-media
@@ -17,6 +17,7 @@ mkdir -p "$watchlater_dir"
 [[ -z "$anime_directory" ]] && anime_directory="$HOME/Videos/Anime"
 [[ -z "$movies_directory" ]] && movies_directory="$HOME/Videos/Movies"
 [[ -z "$shows_directory" ]] && shows_directory="$HOME/Videos/Shows"
+[[ -z "$player" ]] && player="mpv"
 [[ -z "$speed" ]] && speed="1.0"
 
 if [[ ! -f "$fallback_poster" ]]; then
@@ -36,13 +37,13 @@ get_poster(){
 	type="$1"
 	title="$2"
 	year="$3"
-	
+
 	cover_dir="$data_dir/$type"
 	mkdir -p "$cover_dir"
-	
+
 	# Prepare the title argument for the API request
 	encoded_title=$(echo "$title" | tr ' ' '+')
-	
+
 	if [ "$type" == "anime" ]; then
 		# Fetch anime data from Jikan API
 		response=$(curl -s "https://api.jikan.moe/v4/anime?q=$encoded_title&season=$year")
@@ -72,7 +73,7 @@ get_poster(){
 
 process_media(){
 	media_type="$1"
-	
+
 	case "$media_type" in
 		"movies")
 			media_directory="$movies_directory"
@@ -104,7 +105,7 @@ process_media(){
 		notify-send -r 12 -u low -a rofi-media "rofi-media" "Getting posters..."
 		echo ${#lines[@]}
 	fi
-	
+
 	for line in "${lines[@]}"; do
 		# Extract the name of the file from the path
 		name="${line##*/}"
@@ -164,22 +165,43 @@ prompt_menu(){
 	echo -e "$1" | rofi -dmenu -mesg "$2" -theme-str "#mainbox { children: [ message, listview ]; } #textbox { padding: 24px; }"
 }
 
+get_duration(){
+	while [[ -z "$duration" ]]; do
+		# Check if mpv is running and get the duration
+		duration="$([[ "$(pgrep mpv)" ]] && echo '{"command": ["get_property", "duration"]}' | socat - $ipc_socket 2> /dev/null | awk -F'"data":|,' '{print $2}')"
+		
+		# If duration is still empty, wait for 1 second and try again
+		[[ -z "$duration" ]] && sleep 0.5
+	done
+
+	# Once duration is found, save it to the file
+	printf "%.0f" "$duration" > "$watchlater_dir"/duration
+}
+
 play_media() {
 	local file_path="$1"
 	local start_position="$2"
+	local playlist="$watchlater_dir/episode_list.m3u"
+	ipc_socket="/tmp/mpvsocket"
 
 	[[ -z "$start_position" ]] && start_position="0"
-	get_duration &
-	
-	mpv --speed="$speed" --keep-open=always --watch-later-dir="$watchlater_dir" \
-		--write-filename-in-watch-later-config --save-position-on-quit \
-		--start="$start_position" "$file_path" >/dev/null 2>&1
-}
 
-get_duration(){
-	sleep 2
-	duration="$([[ "$(pgrep mpv)" ]]  && echo '{"command": ["get_property", "duration"]}' | socat - /tmp/mpvsocket 2> /dev/null | awk -F'"data":|,' '{print $2}')"
-	[[ -n "$duration" ]] && printf "%.0f" "$duration" > "$watchlater_dir"/duration
+	get_duration &
+
+	if [[ "$player" == "syncplay" ]]; then
+		local episode_list="$(ls -v "${file_path%/*}" | awk -v start="${file_path##*/}" '$0 >= start' > $playlist)"
+
+		syncplay --player-path "$(command -v mpv)" --load-playlist-from-file "$playlist" "$file_path" -- \
+			--speed="$speed" --keep-open=always --watch-later-dir="$watchlater_dir" \
+			--write-filename-in-watch-later-config --save-position-on-quit \
+			--input-ipc-server="$ipc_socket" --start="$start_position" >/dev/null 2>&1
+	elif [[ "$player" == "mpv" ]]; then
+		local episode_list="$(find -L "${file_path%/*}" -maxdepth 1 -type f | sort | awk -v start="$file_path" '$0 >= start' > $playlist)"
+
+		mpv --speed="$speed" --keep-open=always --watch-later-dir="$watchlater_dir" \
+			--write-filename-in-watch-later-config --save-position-on-quit \
+			--input-ipc-server="$ipc_socket" --start="$start_position" "$playlist" >/dev/null 2>&1
+	fi
 }
 
 save_history(){
@@ -188,9 +210,11 @@ save_history(){
 	local duration="$(cat $watchlater_dir/duration 2> /dev/null)"
 
 	file="$(grep -hB1 "start=" $watchlater_dir/* 2>/dev/null | grep -A2 "$name")"
-
+	
+	[[ -z "$file" ]] && echo "History File Not Found!" && exit 1
+	
 	position="$(echo $file | awk -F= '/start/ {print int($2)}')"
-	path="$(echo $file | awk -F' start=' '/^# / {print substr($1, 3)}')"
+	file_path="$(echo $file | awk -F' start=' '/^# / {print substr($1, 3)}')"
 
 	[[ -n "$duration" ]] && local progress=$(($position * 100 / $duration))
 
@@ -198,7 +222,7 @@ save_history(){
 		sed -i "/$name/d" "$media_history"
 	fi
 
-	printf "%s\t%s\t%s\t%s\n" "$name" "$position" "$path" "$progress" >> "$media_history"
+	printf "%s\t%s\t%s\t%s\n" "$name" "$position" "$file_path" "$progress" >> "$media_history"
 
 	rm "$watchlater_dir"/*
 }
@@ -207,10 +231,10 @@ check_history(){
 	local name="${1##*/}"
 
 	position="$(grep -hw "$name" $media_history | awk -F'\t' '{print $2}')"
-	path="$(grep -hw "$name" $media_history | awk -F'\t' '{print $3}')"
+	file_path="$(grep -hw "$name" $media_history | awk -F'\t' '{print $3}')"
 	progress="$(grep -hw "$name" $media_history | awk -F'\t' '{print $4}')"
-	dir="${path%/*}"
-	episode=$(echo "${path##*/}" | sed -n -e 's/.*[eE]\([0-9]\{2\}\).*/\1/p' -e 's/.*\b\([0-9]\{2\}\)\b.*/\1/p' | head -n1)
+	dir="${file_path%/*}"
+	episode=$(echo "${file_path##*/}" | sed -n -e 's/.*[eE]\([0-9]\{2\}\).*/\1/p' -e 's/.*\b\([0-9]\{2\}\)\b.*/\1/p' | head -n1)
 }
 
 prompt(){
@@ -240,12 +264,12 @@ prompt(){
 			prompt "$show"
 			;; 
 		"Resume")
-			play_media "$path" "$position"
+			play_media "$file_path" "$position"
 			save_history "$show"
 			prompt "$show"
 			;;
 		"Replay")
-			play_media "$path"
+			play_media "$file_path"
 			save_history "$show"
 			prompt "$show"
 			;;
@@ -294,17 +318,17 @@ play_history(){
 		next_episode_file=$(ls -v "$selected_directory" | grep -E "S[0-9]+E$next_episode_number| - $next_episode_number - | - $next_episode_number\..*|[_\.x-]$next_episode_number\.")
 
 		if [[ -n "$next_episode_file" ]]; then
-			path="$selected_directory/$next_episode_file"
+			file_path="$selected_directory/$next_episode_file"
 			position=""
 		else 
-			path=""
+			file_path=""
 		fi		
 	fi
 
-	[[ -n "$path" ]] && history=$(prompt_menu "Yes\nNo" "Resume from where you left off?")
+	[[ -n "$file_path" ]] && history=$(prompt_menu "Yes\nNo" "Resume from where you left off?")
 
 	if [[ "$history" == "Yes" ]]; then
-		play_media "$path" "$position"
+		play_media "$file_path" "$position"
 		save_history "$show"
 		[[ -d "$show" ]] &&  prompt "$show"
 		exit 0
@@ -359,7 +383,7 @@ select_episode(){
 	fi
 
 	# Extract episode numbers and titles, and format the selection
-	  selection=$(ls -p "$selected_directory" | grep -v / | grep -E '\.mp4$|\.mkv$' | sed -E '
+	  episode_list="$(ls -p "$selected_directory" | grep -v / | grep -E '\.mp4$|\.mkv$' | sed -E '
 		s/\[.*\] .* - S[0-9]+E([0-9]+).*$/Episode \1/; t;
 		# Handle standard episode formats with season and episode numbers
 		s/.*S[0-9]+[Eex]([0-9]+)[^A-Za-z0-9]*([^0-9]+\S[^0-9]+?)[. ]+[^.]+$/Episode \1: \2/; t;
@@ -375,8 +399,13 @@ select_episode(){
 		# Handle cases where title is complex and episode number is not in the format
 		s/.* - ([^-]+)\..*$/\1/; t;
 		# Fallback for movies or files without episode or season numbers
-		s/.* ([^\/]+)\..*$/\1/' | sed -E 's/\./ /g' \
-		| rofi -sort -dmenu -p "Episode: " -mesg "Select the episode:")
+		s/.* ([^\/]+)\..*$/\1/' | sed -E 's/\./ /g')"
+
+	if [[ $(echo "$episode_list" | wc -l ) -eq 1 ]]; then
+		selection="$episode_list"
+	else
+		selection=$(echo "$episode_list" | rofi -sort -dmenu -p "Episode: " -mesg "Select the episode:")
+	fi
 
 	# Map the selected "Episode X: Title" or title without episode number back to the corresponding file name
 	if [[ -n "$selection" ]]; then
